version: '2'
services:
    api:
        build: .
        environment:
          - MYSQL_HOST=${MYSQL_HOST}
          - MYSQL_PORT=${MYSQL_PORT}
          - MYSQL_DB=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}

        ports:
            - "${API_PORT}:${API_PORT}"
            - "${ARC_PORT}:${ARC_PORT}"
        links:
            - "couchdb:COUCHDB"
            - "redis:REDIS"
            - "db:DB"

        volumes:
          - "$PWD:/home/strongloop"

    db:
        image: percona:5.6
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}

        ports:
          - "${MYSQL_PORT}:${MYSQL_PORT}"

    couchdb:
        image: klaemo/couchdb:1.6
        ports:
          - "${COUCHDB_PORT}:${COUCHDB_PORT}"

    redis:
        image: redis:3
        ports:
          - "${REDIS_PORT}:${REDIS_PORT}"
