version: '2'
services:
    api:
        build: .
        environment:
          - MYSQL_HOST=192.168.99.100
          - HOST=0.0.0.0
          - PORT=4444
        ports:
            - "4444:4444"
        links:
            - "couchdb:COUCHDB"
            - "redis:REDIS"
            - "db:DB"

        volumes:
          - "$PWD:/home/strongloop"

    db:
        image: percona:5.6
        environment:
          MYSQL_ROOT_PASSWORD: somwpwd
        ports:
          - "3306:3306"

    couchdb:
        image: klaemo/couchdb:1.6
        ports:
          - "5984:5984"

    redis:
        image: redis:3
        ports:
          - "6379:6379"
